version: '3.1'

networks:
  ghost:
    external:
      name: ${NETWORK_NAME}

volumes:
  public-content:

services:
  ghost-sitemap:
    container_name: ghost-sitemap
    image: test:test
    env_file: .env
    volumes:
      - public-content:/app/public

  ghost-backup:
    restart: always
    container_name: ghost-backup
    image: bennetimo/ghost-backup
    volumes:
      - ${STORAGE_PATH}:/var/lib/ghost/content
      - ${BACKUP_STORAGE}:/backups
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    networks:
      - ghost

  ghost-front:
    image: deuxmax/ghost-front-react:latest
    container_name: ghost-front
    volumes:
      - public-content:/usr/share/nginx/html/public
      - ${STORAGE_PATH}/ghost/images:/usr/share/nginx/html/images
    ports:
      - ${GHOST_APP_PORT}:80
    networks:
      - ghost

  ghost:
    image: ghost:2-alpine
    container_name: ghost-back
    restart: always
    networks:
      - ghost
    ports:
      - ${GHOST_API_PORT}:2368
    volumes:
      - ${STORAGE_PATH}/ghost:/var/lib/ghost/content
    environment:
      url: ${APP_URL}
      admin: ${ADMIN_URL}
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${DATABASE_ROOT_PASSWORD}
      database__connection__database: ${DATABASE_NAME}

  talk:
    image: coralproject/talk
    container_name: ghost-talk
    restart: always
    networks:
      - ghost
    ports:
      - "${TALK_PORT}:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/coral
      - REDIS_URI=redis://redis:6379
      - SIGNING_SECRET=${TALK_SECRET}
      - TALK_ROOT_URL=${TALK_ROOT_URL}

  db:
    image: mysql:5.7
    restart: always
    networks:
      - ghost
    volumes:
      - ${STORAGE_PATH}/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}

  mongo:
    image: mongo:4.2
    container_name: ghost-talk-mongo
    networks:
      - ghost
    volumes:
      - ${STORAGE_PATH}/mongo:/data/db

  redis:
    image: redis:3.2
    container_name: ghost-tal-redis
    networks:
      - ghost
    volumes:
      - ${STORAGE_PATH}/redis:/data

  prerender:
    image: deuxmax/docker-prerender:latest
    container_name: ghost-prerender
    restart: always
    networks: 
      - ghost
    