version: '3.1'

services:

  ghost:
    image: ghost:2-alpine
    restart: always
    ports:
      - 3001:2368
    volumes:
      - .data/ghost:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - .data/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example